variable "region" { default = "ap-south-1" }
variable "profile" { default = " " }
variable "ami" { default = " " }
variable "availability_zone" { default = " " }
#variable "default_volume_name" { default = "default" }
variable "instance_type" { default = " " }
variable "security_groups" { default = " " }
variable "subnet_id" { default = " " }
variable "private_ip" { default = " " }
variable "instance_name" { default = "my_instance" }